### ISSUE TITLE
Chromely.CefGLue.Gtk.Linux.Demo opens real Chrome browser instead of demo application

### ISSUE THREAD

**Issue by rhombask** [chromelyapps/Chromely#136]
Hi, I am very new here.
I downloaded the demo source code from https://github.com/chromelyapps/demo-projects.
My desktop specification is below
- Ubuntu 18.04
- Visual Studio Code
- .NET Core 3.0 SDK installed
- .NET Core 2.0 SDK installed
- Google Chrome installed(from Google Web Site)

So, when I hit F5 it compiles well and when I hit window.Run(args), the Chrome browser launches and it shows me local://app/chromely.html this file a couple of times.
And now there is an error like below.
And even not launching the Chrome browser either.
2019-11-13 21:46:34.239 [INFO] Running Linux chromium 70.0.3538.102
[1113/214634.410595:ERROR:icu_util.cc(172)] Invalid file descriptor to ICU data received.

Is this normal?
Do I have to uninstall Chrome browser to test properly?

**Comment by FrankPfattheicher** [comment]
Hi @rhombask ,
i assume you try to run "Chromely.CefGlue.Gtk.Linux.Demo".

Yes this opens the browser. The reason is  to run the app for the first time it downloads the CEF libraries. Due this takes a while there is a plain HTML message pages opened in the default browser saying "CEF binaries download started.
Note that depending on your network, this might take up to 4 minutes to complete.
Please wait...".

After that the app tries to run, and YES, there is that error - unfortunately.
Pre netcore 3.0 the build process does not generate an executable :-(

VSCode starts "dotnet Chromely.CefGlue.Gtk.Linux.Demo.dll".
So "dotnet" is the main process which results in that error.
You have to "publish" the app or use netcoreapp3.0 which results in an executabel built.

The VSCode launch.json always starts the DLL using dontet.
I didn't find out how to change...

Starting from the commandline the app works as expected !
I am using netcoreapp3.0 which is preferred and JetBrains Rider as IDE. Here you can remove the DLL extensions in the RUN configuration and it works ;-)

**Comment by rhombask** [comment]
Thanks. I will try and report the result here.

**Comment by rhombask** [comment]
It works fine.
Many thanks.

**Comment by FrankPfattheicher** [comment]
@rhombask as said above: "You have to "publish" the app or use netcoreapp3.0 which results in an executabel built."

I highly recommend using netcore 3!

**Comment by FrankPfattheicher** [comment]
Debug using exe as starting application instead of dll.
Or run app and attach after start...
