### ISSUE TITLE
How to set the cookie of the external link domain

### ISSUE THREAD

**Issue by MingHuiLiu** [chromelyapps/Chromely#137]
How to set the cookie of the external link（url） domain.

**Comment by MingHuiLiu** [comment]
browser property is object type，so I don't know how to set him up.

**Comment by MingHuiLiu** [comment]
external link（url）  Is in the frame element

**Comment by mattkol** [comment]
@MingHuiLiu this is not something that Chromely as supported so far. Chromely is more for creating SPA apps based on local html files. However we see that more and more developers are using it for embedding with external url .. so once in a while we work through issues like that together ..

This issue is similar to . https://github.com/chromelyapps/Chromely/issues/86

This is the closest I have seen to this:

https://groups.google.com/forum/#!topic/cefglue/ADtRW6dRgK0

Ensure that this is done on IO thread .. similar to:
https://github.com/chromelyapps/Chromely/blob/93805e5f4abdebf4ffea143de7dd0423c1e7e1a8/src/Chromely.CefGlue/BrowserWindow/HostBase.cs#L524

Please keep us posted.
