### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by xplicit** [chromelyapps/Chromely#150]
Is it possible to create dark theme using chromely? Similar to VS Code, when title bar/close/maximize button are black and it's possible to resize and drag main window.

**Comment by mattkol** [comment]
@xplicit yes, you can create dark theme using Chromely but it not supported. To do that you have to make changes to the code.

It will require making the host Window frameless and creating a custom tittle bar.

This was attempted for Windows 10 previously in [Chromely.Legacy](https://github.com/chromelyapps/Chromely/issues/96) but was not conclusive because of the subjective approaches. Demos can be found [here](https://github.com/chromelyapps/Chromely.Legacy/tree/master/Demos/regular-chromely/frameless_draggable_command).

If it is something you are interested in you can use the info if helpful, but we will not be supporting it for now.

Thanks,

**Comment by xplicit** [comment]
Thanks, this is very helpful, I'll look into demos/code for getting more details how to implement this. Just a question: do you expect these demos should be compatible with Win7 or they will run only on Win10? We tried to do resizing on frameless window for both win7/win10 previously but without success (on win7 there is huge border which breaks the code working flawless on Win10).

For the demos I noticed that resizing stops work after dragging the window (on Win10).

**Comment by mattkol** [comment]
@xplicit this solution was never tested on win7 as far as I know, so I do not have that much info on that. In my opinion they should run on win7. We use basic win32 pinvoke functionalities.

For the demos: you may have to play with the following properties to get resizing to work:

````
      .WithHostFlag(HostFlagKey.CenterScreen, true | false - default true)
      .WithHostFlag(HostFlagKey.Frameless, true) // | false -  default false)
      .WithHostFlag(HostFlagKey.KioskMode, true) // | false - default false)
      .WithHostFlag(HostFlagKey.NoResize, true) // - default false)
      .WithHostFlag(HostFlagKey.NoMinMaxBoxes, true) // - default false)
````

If possible please get latest, but note that this solution is not ultimate, just provided as-is for developers who want to take it to the next level.

Thanks.
