### ISSUE TITLE
AJAX requests to external API is not working from frontend app

### ISSUE THREAD

**Issue by donotcodeit** [chromelyapps/Chromely#156]
Is it possible to send AJAX request to an external API endpoint from front-end application?
Currently I am unable to do it. Any request I'm sending returns valid headers, as if request were sent and response received, but response body is empty.

**Comment by mattkol** [comment]
@donotcodeit 

We see less questions on Ajax calls, which tells me that developers use it less.

But is this related to these:

[comment](https://github.com/chromelyapps/Chromely/pull/88#issuecomment-508931347)
[issue](https://github.com/chromelyapps/Chromely/issues/108)
[handler](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.CefGlue/Browser/Handlers/ExternalRequestSchemeHandler.cs)

If not, we may have to look closely.

Thanks.

**Comment by donotcodeit** [comment]
Looks like that handler was not registered. I've added and tested some changes - with them external AJAX requests working as expected. Take a look at https://github.com/chromelyapps/Chromely/pull/157 please.

**Comment by mattkol** [comment]
@donotcodeit  the non-registration is intentional. The handler was just carried over for developers who may have similar requirements - and from experience - very few.

Yes we can add it as default handler, but we need to either re-use the "Custom" type or add a new type like "CustomExternal" or anything that makes sense.

The "External" url scheme you used is designed to launch a url in the OS default browser.

Please see [1](https://github.com/chromelyapps/demo-projects/blob/5d075a31d335ca7b64750555e4765eb1b854b203/regular-chromely/CrossPlatDemo/chromelyconfig.json#L53), [2](https://github.com/chromelyapps/demo-projects/blob/5d075a31d335ca7b64750555e4765eb1b854b203/regular-chromely/CrossPlatDemo/app/pages/home.html#L77) and [3](https://github.com/chromelyapps/Chromely/blob/1a358986894377da8cffe87e00ce0d5893db690b/src/Chromely.CefGlue/Browser/Handlers/CefGlueRequestHandler.cs#L72).

Thanks.

**Comment by donotcodeit** [comment]
Thanks for explanation. I got your point. So what is the correct way to register this handler w/o changing the Chromely source codes?

**Comment by donotcodeit** [comment]
> Yes we can add it as default handler, but we need to either re-use the "Custom" type or add a new type like "CustomExternal" or anything that makes sense.

I can suggest to add it as `ajax` or `api` URL scheme to have this functional out of the box. I can adjust PR if you want.

**Comment by mattkol** [comment]
Without code change - "Custom":
[Custom Reg](https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_scheme_handlers.md)

Full documentation
[Doc](https://github.com/chromelyapps/Chromely/blob/master/Documents/ajax_xhr_request_handling.md)

Yes, using "Ajax" or "AjaxCustom" should work to add functionality out of the box.

If we conclude on https://github.com/chromelyapps/Chromely/issues/153 too we can make a nuget build.

Thanks.

**Comment by donotcodeit** [comment]
> Yes, using "Ajax" or "AjaxCustom" should work to add functionality out of the box.

Ok, I'll update the pull request.

> If we conclude on #153 too we can make a nuget build.
Please wait. I'll make an update with fixes for it today.

**Comment by donotcodeit** [comment]
> Ok, I'll update the pull request.

Done https://github.com/chromelyapps/Chromely/pull/157

**Comment by mattkol** [comment]
@donotcodeit thanks for your efforts on this.
I think we can close the 2 stories now.
I updated nugets to pre04. We should get the final one done soon.
Thanks.

**Comment by donotcodeit** [comment]
Thank you for the release.

> I think we can close the 2 stories now.

I agree. Will close both.
