### ISSUE TITLE
Content does not resized while resizing frameless window

### ISSUE THREAD

**Issue by donotcodeit** [chromelyapps/Chromely#161]
After some changes for https://github.com/chromelyapps/Chromely/issues/153 we did broke resizing of frameless window. I was unable to find the certain commit.

Before and expected: browser window has its content resized while doing resize on the host window.
Now: browser window will resize its content only when resizing stopped.

**Comment by mattkol** [comment]
Tricky, sensitive stuff, this frameless window. I will take sometime to look too.
Thanks for letting us know.

**Comment by daricvn** [comment]
I don't know if it's appropriate to post it here but currently latest version of chromium seem cause some other critical issue with new Frameless Windows now. 
It only happens when you disable MultiThreadedMessageLoop on  Windows Chromium 79.0.3945.130.
I received _Failed to initialize CategoryMgr_ message from Chromium when trying to run the app.

I'm looking for a way to resolve this issue.

**Comment by mattkol** [comment]
@daricvn we can track it here too.
Thanks for letting us know.

**Comment by mattkol** [comment]
@donotcodeit  @daricvn I will like to close this for now. 
Please let us see if the v5.1 release fixes this, if not we can start afresh with a new issue or reopen.
