### ISSUE TITLE
Running in virtual machine supported?

### ISSUE THREAD

**Issue by SirePi** [chromelyapps/Chromely#167]
I'm trying to test the library under linux, but whenever I run the program that works without issues in Windows I end up with this kind of error saying that the gpu-process crashes

Initially I had a libX11.so not found, so I installed libx11-dev, but the segfault remained

```
pi@pi-VirtualBox:~/Downloads/linux-x64$ ./crossplatdemo
2020-03-07 15:54:52.235 [INFO] Running Linux chromium 77.0.3865.120
On CefGlue child process launch arguments:
/proc/self/exe --type=gpu-process --field-trial-handle=8883176290764582883,17956091608203660837,131072 --disable-features=OutOfBlinkCors --no-sandbox --locales-dir-path=/home/pi/Downloads/linux-x64/locales --log-file=logs\chromely.cef_20200307.log --log-severity=info --resources-dir-path=/home/pi/Downloads/linux-x64/ --lang=en-US --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
2020-03-07 15:54:56.748 [INFO] Running Linux chromium 77.0.3865.120

DevTools listening on ws://127.0.0.1:20480/devtools/browser/d89227bb-7026-4581-a6ee-64c402dcb411
[0307/155457.575608:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
On CefGlue child process launch arguments:
/proc/self/exe --type=utility --field-trial-handle=8883176290764582883,17956091608203660837,131072 --disable-features=OutOfBlinkCors --lang=en-US --service-sandbox-type=network --no-sandbox --locales-dir-path=/home/pi/Downloads/linux-x64/locales --log-file=logs\chromely.cef_20200307.log --log-severity=info --resources-dir-path=/home/pi/Downloads/linux-x64/ --lang=en-US --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
2020-03-07 15:54:58.365 [INFO] Running Linux chromium 77.0.3865.120
2020-03-07 15:54:58.429 [WARNING] Request Code: 1	Request Type: X_CreateWindow	X11 Error: BadRequest (invalid request code or no such operation)
Segmentation fault
2020-03-07 15:54:58.514 [INFO] Sub process executes successfully with code: 0
```

is it possible it's due to the fact that I'm running it in a virtual machine?

**Comment by mattkol** [comment]
@SirePi yes, you can run Chromely in VMs. I have used VMs and DigitalOcean droplets to test Chromely apps.

I won't go as far as saying we support Chromely on VMs because that could mean a whole lot of things. There are variations of distros out there and different ways to access them via VMs.

Yes, there is a possibility that the issue you are seeing is VM related or missing libs. It is like X11 is failing to actually create a window for gtk. 

CEF itself seems to be running as expected:
````
2020-03-07 15:54:58.514 [INFO] Sub process executes successfully with code: 0
````

What distro/version are you running? Personally I have tested on Linux - Lint Mint Xfce (Ubuntu 18.04.3 LTS), Linux Mint 19.3 Tricia, Ubuntu 19.10 (x64

You can try a fresh setup of your VM. Or try a different distro/version of Linux.

Please ensure that you have gtk3 libs installed.

Also check https://github.com/chromelyapps/Chromely/issues/163. @snairza may also be able to help as he recently had a closely related issue.

**Comment by SirePi** [comment]
I'll try with an ubuntu.. I was trying it on ElementaryOS 5.1

**Comment by SirePi** [comment]
Can confirm that on Ubuntu 18.04 it works properly after installing libx11-dev 👍

**Comment by snairza** [comment]
I have confirmed that 18.04 works, however I seem to have a problem in
16.04 where the Cromely browser starts up but no content is rendered - only
a white screen.

**Comment by FrankPfattheicher** [comment]
@snairza Installed 16.04 - does not work at all
Installed updates AND libx11-dev
Now it works on my VirtualBox VM

**Comment by snairza** [comment]
I cloned the project again and can confirm it now works! Thanks guys!
