### ISSUE TITLE
Chromely Ajax XHR Request Handling Security

### ISSUE THREAD

**Issue by greenstone90** [chromelyapps/Chromely#176]
Chromely seems like a great project!

If I'm understanding right, when using Ajax XHR Request Handling, Chromely is really an http/html client in the browser, served by an http server.  From a security point of view, what provisions keep any http client from doing POST/GETs from the "server"?

Thanks!

**Comment by piloitte** [comment]
@greenstone90 

This is an interesting question.

In a way, yes, client/http server. But more a self-contained client/server application. So both request and response are within a restricted context.

So I doubt that any request made externally or otherwise out of that context will be accepted. I have tried many times. But maybe there are scenarios I have not tried. Will be nice to know.

Having said that developers can put enough security and access control around their resources. Like any other Restful resource security implementation.

Resouces as in [Controllers](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo/Controllers) and [Controllers Actions](https://github.com/chromelyapps/demo-projects/blob/4972e12513112877275a8476a6acb3643a970abe/regular-chromely/CrossPlatDemo/Controllers/DemoController.cs#L77).

Alternative will be to use [Message Router](https://github.com/chromelyapps/Chromely/blob/master/Documents/generic_message_routing.md). But even using Message Router, the security and access control should still be implemented if deemed necessary.

**Comment by mattkol** [comment]
@greenstone90 

This is an interesting question.

In a way, yes, client/http server. But more a self-contained client/server application. So both request and response are within a restricted context.

So I doubt that any request made externally or otherwise out of that context will be accepted. I have tried many times. But maybe there are scenarios I have not tried. Will be nice to know.

Having said that developers can put enough security and access control around their resources. Like any other Restful resource security implementation.

Resouces as in [Controllers](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo/Controllers) and [Controllers Actions](https://github.com/chromelyapps/demo-projects/blob/4972e12513112877275a8476a6acb3643a970abe/regular-chromely/CrossPlatDemo/Controllers/DemoController.cs#L77).

Alternative will be to use [Message Router](https://github.com/chromelyapps/Chromely/blob/master/Documents/generic_message_routing.md). But even using Message Router, the security and access control should still be implemented if deemed necessary.

**Comment by greenstone90** [comment]
Thanks for the thoughts on it!
