### ISSUE TITLE
Is there a performance difference between Restful methods

### ISSUE THREAD

**Issue by ShravanSunder** [chromelyapps/Chromely#198]
Is there any reason you would pick one of the following methods?  

- HTTP/XHR - scheme://domain/controller/action
- JSObjects - /controller/action
- cefQuery - /controller/action

Any performance differences or optimal usecases, where i should use cefQuery?

**Comment by mattkol** [comment]
@ShravanSunder  I will pick

- cefQuery - /controller/action 
because it is native CEF.

The reason I will pick HTTP/XHR will be for some backward compatibility issues - all the html have been previously done in HTTP/XHR, so no need to convert to cefQuery.

JSObjects - this was CefSharp, I believe. 

Performance wise, personally, I have not looked closely, but my gut will be cefQuery will be faster - no extra dependencies - done in CEF. Will be a fun thing to look at for sure.

Nice question, thanks.
