### ISSUE TITLE
[Question] It is possible to have more than one embedded Browser in a Window?

### ISSUE THREAD

**Issue by stevendevit** [chromelyapps/Chromely#202]
Hi! You might heard about LG Web Os. It is a Web Based OS that can run web-based technologies apps. They use Chromium internally.

**Lg Web Os Architecture:**
https://www.webosose.org/docs/guides/core-topics/architecture/architecture-overview/

**Lg WebOs Dashboard:**
[
![imagen](https://user-images.githubusercontent.com/20980018/82143410-1540fc80-9844-11ea-8c0c-42f27ddca132.png)
](url)

My goal is to make a Kiosk App that can run and switch between "Apps" (embedded browsers running web based apps). The behaviour might be like switching between tabs like a plain Web Browser. Any idea?

This project suites my needs but is not Cross Platform 
[https://github.com/cefsharp/CefSharp](url)

Thanks!

**Comment by mattkol** [comment]
@stevendevit Chromely is a one-browser/one-app framework by design.

What you want to do is off course possible, but will require some work. You may need child controls like static controls for Windows (and similar ones for Gtk/Cocoa). 

Please see my comment https://github.com/chromelyapps/Chromely/issues/119#issuecomment-522370496 related to this.
