### ISSUE TITLE
OnBeforeClose does not run till end

### ISSUE THREAD

**Issue by xplicit** [chromelyapps/Chromely#204]
I added OnBeforeClose event handler similar to

https://github.com/chromelyapps/Chromely/blob/81b8231cf4321c05e2689be4407c3c85076f68db/src/Chromely/ChromelyEventedApp.cs

But when chromely is closed the method `OnBeforeClose()` does not run till end if code in the event hadler take some time to execute. You can catch it by adding 

        protected virtual void OnBeforeClose(object sender, BeforeCloseEventArgs eventArgs)
        {
              Thread.Sleep(10000); //Or Task.Delay(10000).Wait();
              Console.WriteLine("Closing");
        }

Console.WriteLine() will never be executed

This is because of parallel execution of closing window and `OnBeforeClose` event at this line

https://github.com/chromelyapps/Chromely/blob/81b8231cf4321c05e2689be4407c3c85076f68db/src/Chromely/Windows/Window.cs#L70

If make it synchronous then `Dispose()` ends after `OnBeforeClose()` event and all works as expected

**Comment by mattkol** [comment]
@xplicit great catch!

It's been an issue that has been bugging me for a while, and never had the chance to properly zoom in on it. At some point I thought it was just happening locally for me.

I will see about making the change over the weekend.

Thanks.

**Comment by xplicit** [comment]
It would be great, if we can to cancel closing inside this event. For example, user press Alt+F4, we cancel the closing and ask user ("You have unsaved work, do you really want to close?" [OK], [Cancel]).

**Comment by mattkol** [comment]
@xplicit  I won't advise that. CEF processes are tricky - even this OnBeforeClose approach for now is a hack  - https://github.com/chromelyapps/Chromely/blob/6b02086ba3360d3baa706ebddb21158b3d85d8da/src/Chromely/Windows/Window.cs#L74

It was discovered late after the release, and I have personally not have enough time to dig deeper because a fix in Windows may break Linus/MacOS and vice-versa. It needs time. 

What you are trying to do I will suggest you do in the [native host](https://github.com/chromelyapps/Chromely/blob/6b02086ba3360d3baa706ebddb21158b3d85d8da/src/Chromely/Native/WinAPI/WinAPIHost.cs#L465) but that will involve creating a custom one.

I think a more comprehensive  OnClose  feature should be added for a major release.

**Comment by xplicit** [comment]
Thanks, your suggestion helped to resolve the issue with properly tracking "close" event. We use `Close` event from `WinAPIHost` - it's called synchronously. If we need to cancel the event, we can override `WndProc()` for now.
