### ISSUE TITLE
Chromely run on centos7.0 

### ISSUE THREAD

**Issue by DavidDXY** [chromelyapps/Chromely#208]
i try run chromely demo on centos7.0,but it did not work, i use "ldd libcef.so",fix the Dependence,seem like the version79 not suported on centos7.0, but the version58 of libcefsimple project can run on the centos7.0.how can i use the version58 of libcef by chromely

**Comment by mattkol** [comment]
Version58 is a much older version and so many things have changed since then, but you can try.
You need to search for CefGlue version58 [here](https://bitbucket.org/xilium/xilium.cefglue/downloads/?tab=branches) and replace the relevant core CefGlue code with [Chromely CefGlue Folder](https://github.com/chromelyapps/Chromely/tree/master/src/Chromely.CefGlue/CefGlue) and see what happens.

The [older Chromely](https://github.com/chromelyapps/Chromely.Legacy) may most likely will work because first Chromely version is [version59](https://www.nuget.org/packages/Chromely.Unofficial.CefGlue.NetStd/59.0.3071.109) and I am not sure if that is that straightforward either.
