### ISSUE TITLE
Allow to change serialization naming policy

### ISSUE THREAD

**Issue by Jluil** [chromelyapps/Chromely#209]
Allow to change serialization naming policy to JsonNamingPolicy.CamelCase.
This behavior is now standard for .NET core services, where .NET has PascalCase properties and client web app uses CamelCase properties.

**Comment by mattkol** [comment]
@Jluil is the suggestion to make  JsonNamingPolicy.CamelCase the default globally or allow to make it configurable?

Not sure we can force a default globally the way we are setup currently. I have not looked closely, there may be a way.

Just FYI the next version of Chromely will use [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection). I have looked at it closely and it seems light enough for Chromely. So this will replace - [Caliburn.Light Container](https://caliburnmicro.com/documentation/simple-container).

So with this, change should be easy for developers to make.

We just need to create bandwidth for that.

Good point!  👍

**Comment by Jluil** [comment]
Hey, thanks for the response.
It would be ideal if the options were configurable, but I think CamelCase policy could even be default.
I briefly looked through the codes and currently SerializationOptions are static within some utility class. Having them injected/configurable would be nice.
I really like the project and I'm currently testing the server-client communication. I might a few more suggestions.. hope you don't mind:)

**Comment by mattkol** [comment]
@Jluil by Utility class, you mean int the [Extension method](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Network/ExtensionMethods.cs)? Sure, that can be improved. Thanks for pointing it out.

> Having them injected/configurable would be nice.

This needs to be thought through. The use of System.Text.Json is more of a suggestive use rather than a standard. Chromely more or less uses it in default classes. Those classes are replaceable and customizable. So in essence the serializing library can be replaced. Developers are not necessarily tied to System.Text.Json. They can use any serializing library.

Like I mentioned earlier, we will see how all these fit in when we move to Microsoft.Extensions.DependencyInjection.
 
Suggestions are always welcome.

Thanks.

**Comment by Jluil** [comment]
It's really nice that .NET has it's own Json serializer that can do stuff like PascalCase to camelCase conversion by simply changing: PropertyNamingPolicy = JsonNamingPolicy.CamelCase.

**Comment by FrankPfattheicher** [comment]
For Newtonsoft.JSON this could be

```
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
                {
                    NamingStrategy = new CamelCaseNamingStrategy()
                } 
            };
```
