### ISSUE TITLE
Add support for route params

### ISSUE THREAD

**Issue by Jluil** [chromelyapps/Chromely#212]
It is standard for web service routes in different platforms and librarties to support route params such as  "/product/1" where the routes could for example be defined as "/product/:productId" or "/product/{productId}".
Currently routes are absolutely matched so it is not possible to do this, probably some more extensive changes like regex path matching would be needed.

**Comment by mattkol** [comment]
@Jluil it is easy to tend to mimic Chromely use of Restful pattern with what an actual API does. While they seem similar it is not the same. The use of Restful pattern is a choice because of its popularity and not needed to do what Chromely needs to do. A unique key can also be used.

For Chromely these patterns can be used and will be fine
````
 "url": "/tmdbmoviescontroller/movies"
 "key": "6271a62b-d6b7-4e5e-a9d4-7ecb48f82196"
````
You can use the parameter property to do the same:
https://github.com/chromelyapps/Chromely/blob/4a1319f5bac4628400d94fb088d615bbb34c7926/src/Chromely.Core/Network/ChromelyRequest.cs#L53

In JavaScript:
````
var request = {
      "method": method,
      "url": url
      "parameters": parameters,
      "postData": postData,
 };
````

**Comment by Jluil** [comment]
ok but this does not work with http requests via custom-http scheme only with javascript api right?

**Comment by mattkol** [comment]
@Jluil good point.

That is handled a bit differently. Query parameters are turned into parameters for custom-http

````
http://chromely.com/democontroller/movies?name=MyName&Age=12
````
https://github.com/chromelyapps/Chromely/blob/fdf33e529d2f9b1a8006d73c91c40fe6b660c9db/src/Chromely.CefGlue/Browser/Handlers/CefGlueHttpSchemeHandler.cs#L80

The alternative is to put everything in as the data object
````

var request = {
      "method": method,
      "url": url
      "parameters": parameters,
      "postData": postData,
 };
  var http = new XMLHttpRequest();
            var url = "http://chromely.com/externalcontroller/movies";
            http.open("GET", url, true);
			...
	http.send(JSON.stringify(request ));
````

**Comment by Jluil** [comment]
Ok thanks, with a little bit of boilerplating I am able to work with that.
