### ISSUE TITLE
How to return 404, 403 or any error code to renderer process ?

### ISSUE THREAD

**Issue by redplane** [chromelyapps/Chromely#219]
Hi, 

I'm using chromely for my desktop app development.
Till now, everything seems to be OK.
However, when I try to return HttpStatusCode which is about Http errors, such as: 401, 403, 404, every time ajax is done, the response is always 200.

FYI, this is what I'm doing:

```
protected virtual async Task<ChromelyResponse> EstablishSerialPortConnectionAsync(ChromelyRequest request)
        {
            var model = JsonConvert.DeserializeObject<EstablishConnectionViewModel>(request.PostData.ToJson());
            var response = new ChromelyResponse();
            try
            {
                await _serialPortConnectionService.ConnectAsync(model);
            }
            catch (Exception exception)
            {
                response.Status = (int)HttpStatusCode.InternalServerError;

                if ((exception is ArgumentException))
                    response.StatusText = HttpResponseMessageCodes.InvalidSerialPortSettings;

                if (exception is IOException)
                    response.StatusText = HttpResponseMessageCodes.InvalidSerialPortState;

                if (exception is InvalidOperationException)
                    response.StatusText = HttpResponseMessageCodes.SerialPortAlreadyOccupied;
            }
           
            return response;
        }
```

Any tutorial about this please ?

**Comment by mattkol** [comment]
@redplane  this is a rather simple but somewhat complicated decision when you are trying to go with an approach. The question here is what should the default value be - OK (200) or some error code since most developers do not set this anyway? So what we have had from the beginning is to ignore that even if set by developer. So for simple processing it is either OK (200) or BadRequest (400).

https://github.com/chromelyapps/Chromely/blob/fbd02e3f63322dd63c5afa9a267825013c7ef7ae/src/Chromely.Core/Defaults/DefaultRequestTaskRunner.cs#L178

https://github.com/chromelyapps/Chromely/blob/fbd02e3f63322dd63c5afa9a267825013c7ef7ae/src/Chromely.Core/Defaults/DefaultRequestTaskRunner.cs#L240

**But I think it is high time we changed that. This will be revisited.** 

The way this has worked for other developers is to wrap the payload response itself as the Data.
Please see - https://github.com/chromelyapps/Chromely/issues/110#issuecomment-514040680

````csharp
private static ChromelyResponse Connect(ChromelyRequest request)
{
       var content = new SomeClass() {
	       Status = 404,
		StatusText = "Not Found",
		Data = "No Data"
       }
	return new ChromelyResponse(request.Id)
	{
		Data = content
	}
}
````

Thanks.

**Comment by redplane** [comment]
For now, I'm using your above workaround. 
But I think it is necessary to return error http status code because many web application, developers handle the error using HttpStatusCode (at least the developers I know are doing that)

**Comment by redplane** [comment]
Imo, this issue shouldnt be closed, because http status code is necessary for front end to handle exceptions

**Comment by mattkol** [comment]
@redplane please read my comment closely.

> But I think it is high time we changed that. This will be revisited.

You said the workaround works, right? The change is simple, but one needs to spend time to see what else will be impacted, so let us spend sometime to make that improvement. If you want to leave it opened until it is resolved, you can go ahead and do that. 

Very soon I will create a master list of what will be included in next release. This will be part of it. You can check back to see when.

But no promises on timeline. 

Thanks.

**Comment by mattkol** [comment]
@redplane this - https://github.com/chromelyapps/Chromely/commit/afda7d1eaa866790b6db029151fcd9303c15d915 is the minimal change that I think is required, If you are able to help confirm, that it is all that is needed, that will be fine. But I am unable to re-confirm for now. If you cannot confirm it, I will revisit it later.

Thanks.
