### ISSUE TITLE
Howto: Save and Restore Window Position and Size

### ISSUE THREAD

**Issue by mattkol** [chromelyapps/Chromely#279]
[WindowPlacementDemo.zip](https://github.com/chromelyapps/Chromely/files/5761674/WindowPlacementDemo.zip)

````c#
   class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            AppBuilder
            .Create()
            .UseApp<DemoApp>()
            .Build()
            .Run(args);
        }
    }

    public class DemoApp : ChromelyBasicApp
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            base.ConfigureServices(services);
            services.AddSingleton<IChromelyAppSettings, CustomAppSettings>();
        }
    }

    public class CustomAppSettings : DefaultAppSettings
    {
        private const string WINPOSLEFT =  nameof(WINPOSLEFT);
        private const string WINPOSTOP = nameof(WINPOSTOP);
        private const string WINPOSWIDTH = nameof(WINPOSWIDTH);
        private const string WINPOSHEIGHT = nameof(WINPOSHEIGHT);

        private IChromelyNativeHost _nativeHost;

        public CustomAppSettings(IChromelyNativeHost nativeHost)
        {
            _nativeHost = nativeHost;
        }

        public override void Read(IChromelyConfiguration config)
        {
            try
            {
                base.Read(config);

                ChromelyDynamic chromelyDynamic = Settings as ChromelyDynamic;
                if (chromelyDynamic != null)
                {
                    IDictionary<string, object> settingsDic = chromelyDynamic.Dictionary;
                    int left = 0;
                    int top = 0;
                    int width = 0;
                    int height = 0;

                    if (settingsDic.ContainsKey(WINPOSLEFT)) left = (int)Convert.ChangeType(settingsDic[WINPOSLEFT], typeof(int)); 
                    if (settingsDic.ContainsKey(WINPOSTOP)) top = (int)Convert.ChangeType(settingsDic[WINPOSTOP], typeof(int));
                    if (settingsDic.ContainsKey(WINPOSWIDTH)) width = (int)Convert.ChangeType(settingsDic[WINPOSWIDTH], typeof(int));
                    if (settingsDic.ContainsKey(WINPOSHEIGHT)) height = (int)Convert.ChangeType(settingsDic[WINPOSHEIGHT], typeof(int));

                    if (width > 0 && height > 0)
                    {
                        config.WindowOptions.Position = new WindowPosition(left, top);
                        config.WindowOptions.Size = new WindowSize(width, height);
                    }
                }

            }
            catch { }
        }

        public override void Save(IChromelyConfiguration config)
        {
            try
            {
                if (_nativeHost != null && _nativeHost.Handle != IntPtr.Zero)
                {
                    WINDOWPLACEMENT winPlacement;
                    GetWindowPlacement(_nativeHost.Handle, out winPlacement);
                    Settings.WINPOSLEFT = winPlacement.rcNormalPosition.X;
                    Settings.WINPOSTOP = winPlacement.rcNormalPosition.Y;
                    Settings.WINPOSWIDTH = winPlacement.rcNormalPosition.Width;
                    Settings.WINPOSHEIGHT = winPlacement.rcNormalPosition.Height;
                }

                base.Save(config);
            }
            catch { }

        }
    }
````

**Comment by wwarby** [comment]
Ah thanks so much for taking the time to put that together. There were a couple of issues with the demo you created - first was I needed to add  `config.WindowOptions.StartCentered = false;` to stop it overriding the window position on startup, second was I needed to use `GetWindowRect` instead of `GetWindowPlacement` because `GetWindowPlacement` reports incorrect window placement when the window has been docked to the left or right half of the screen with "Aero Snap" (basically when you drag the window to the left of the screen and "dock" it, it returns the last position the window was in before the docking happened).

I'll put together a more comprehensive demo over the next couple of days that covered the above issues and remembers max/min state of the window too once I've incorporated the behaviour into my own app.

My gut feeling is that what you've outlined here is a good solution to the problem and now that it's publicly documented people will be able to find and follow how to do it, but it does seem that you could (and perhaps should) neatly encapsulate the behaviour into a setting that can be turned on without creating a custom settings class. Restoring a application's window to the same size and position between runs is a pretty common requirement for desktop apps so I think it should be easy functionality to reach if feasible.

**Comment by mattkol** [comment]
@wwarby 

I am actually just seeing your comment. Usually I get an alert. Well ...

Yes, when I was creating the demo, I thought about including it too. With a cross-platform project, one has to think about all platforms. But sure we can start with Windows.

Please let me know when the comprehensive demo is ready. We can also reopen this or create a new issue to track it.

Thanks.
