### ISSUE TITLE
Changes to LocalStorage lost if Chromely app is closed too quickly after writing value

### ISSUE THREAD

**Issue by RobertBouillon** [chromelyapps/Chromely#293]
If the Chromely application host is closed within about 5 seconds of writing data to LocalStorage, the latest writes are lost.

There appears to be some sort of lazy process which persists the contents of LocalStorage to disk, which is being aborted too soon.

Do I need to invoke some method or explicitly dispose of some object when the application quits?

**Comment by mattkol** [comment]
@RobertBouillon 
This may help -https://github.com/chromelyapps/Chromely/issues/168

**Comment by RobertBouillon** [comment]
@mattkol 

I believe my issue is different.

Consider the following two scenarios:

**Scenario 1**
1. Write data to LocalStorage
2. **Immediately close** Chromely
3. Open Application
4. Saved data is **lost**

**Scenario 2**
1. Write data to LocalStorage
2. **Wait 10 seconds** to close, then close application
3. Open Application
4. Saved data is **Retained**

It seems there's a lazy writer which I'm preempting when I close the application. If I "save and close," there's a chance that I haven't actually saved, and I've lost data.

    private static void SetupFileSystem(IChromelyConfiguration config)
    {
      var docs = new OsDirectory(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments));
      var tempus = docs.GetDirectory("Tempus");
      var cache = tempus.GetDirectory("Data");
      var reports = tempus.GetDirectory("Reports");

      if (!tempus.Exists())
        tempus.Create();

      if (!cache.Exists())
        cache.Create();

      if (!reports.Exists())
        reports.Create();

      config.CustomSettings["CachePath"] = cache.FullName;
    }
```
```

**Comment by mattkol** [comment]
This is the closest I see to what you described - https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=13645
> You have to release all browser references (and probably other CefRefPtr as well) when closing app before calling CefShutdown

On what OS is this happening? There was an outstanding [issue](https://github.com/captainjono/Chromely/issues/1) with shutdown process in MacOS - may be related.

**Comment by RobertBouillon** [comment]
This is Win 10. Happens in dev and prod.

Is there anything I can call that's exposed out of Chromely? What if I pull the source and add a reference that way? Anything I might be able to poke when the app shuts down?

**Comment by mattkol** [comment]
> Is there anything I can call that's exposed out of Chromely?

Nothing that I am aware of. Chromely does not touch localStorage implementation but some of our actions may have prevented a proper shutdown that is impacting that.

> Anything I might be able to poke when the app shuts down?

This is usually a conflict between Windows (host) shutdown and CEF shutdown. We may have to look at the steps closely - starting from - [Close](https://github.com/chromelyapps/Chromely/blob/3622bc432a8f48181d78ec7720816a7fe4fd0654/src/Chromely/NativeHosts/WinHost/WinBase/NativeHostBase.cs#L559)  or [Destroy](https://github.com/chromelyapps/Chromely/blob/3622bc432a8f48181d78ec7720816a7fe4fd0654/src/Chromely/NativeHosts/WinHost/WinBase/NativeHostBase.cs#L571)

I looked around and it seems not an uncommon problem - [Electron issue](https://github.com/electron/electron/issues/3895). Electron has a solution -  [FlushStorageData](https://github.com/electron/electron/commit/489539d62e4150c61d42600d847351d90cab7bae#diff-e389d7e9e83943a2419be90b3a1752f9f6dfcc9cbf733ef4ff4a1659d7dd0e9cR315). 
This is similar to what was done for cookies - https://github.com/chromelyapps/Chromely/issues/259#issuecomment-732829390

There CEF community had use of  [enable-aggressive-domstorage-flushing](https://bitbucket.org/chromiumembedded/cef/issues/2063/add-api-for-programmatically-flushing) switch. Maybe a temporary fix if it works.

My suggestion is that you help create a simple one page html and we can debug using base Chromely implementation to track it and see if it is something we can resolve here, otherwise we resort to CefGlue or CEF for help.

**Comment by RobertBouillon** [comment]
I like the idea of creating a simple one-page HTML app to reproduce the issue. I'll need a couple of days, as this is a lower priority (we have a workaround), but I'll put something together. Thanks!

**Comment by mattkol** [comment]
@RobertBouillon I could not reproduce this. Please reopen if need be.
Attached is what I used.
[localStorage.zip](https://github.com/chromelyapps/Chromely/files/6218617/localStorage.zip)
