### ISSUE TITLE
Backspace in kiosk mode not working

### ISSUE THREAD

**Issue by software-driven** [chromelyapps/Chromely#331]
When the kiosk mode is activated, it is quite inconvenient to delete inputs from a text field, since the backspace key does not work. Is it possible to allow this key?

**Comment by mattkol** [comment]
@software-driven 
It could be due to this:
https://github.com/chromelyapps/Chromely/blob/3cdb28e16182651e7fbec193593c07343e657e85/src/Chromely/NativeHosts/WinHost/WinBase/DefaulKeyboadHookHandler.cs#L82

This part of kiosk mode was contributed by @Soarc  and was well tested at the time. If this is the issue, there may be a good reason why it was disallowed, but I do not know if it is a standard for kiosk mode or just specific to what @Soarc  was doing at the time. 

Meanwhile I will suggest you try remove that and see, by creating a custom keyboard handler using the [default implemetation](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/NativeHosts/WinHost/WinBase/DefaulKeyboadHookHandler.cs).

````cs
    public class DemoApp : ChromelyBasicApp
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            base.ConfigureServices(services);
            services.TryAddSingleton<IKeyboadHookHandler, CustomKeyboadHookHandler>();

            ----
        }
    }

    public class CustomKeyboadHookHandler : IKeyboadHookHandler
    {
    }
````

Based on your feedback, we can update the default implementation. If @Soarc  respond too, we can use both feedbacks.

**Comment by software-driven** [comment]
@mattkol thank you for your prompt reply. As suggested, I have created a custom implementation based on the default. 

`if (key < Keys.Back ||` instead of  `if (key <= Keys.Back ||` fixes the issue with the backspace key.

**Comment by Soarc** [comment]
If I remember correctly, I added because it, because it was possible to go on initial screen using back button and broke kiosk mode. I'm not sure, if it still case.

**Comment by mattkol** [comment]
Thanks for the feedback @Soarc. @software-driven please let me know if your fix is still valid based on @Soarc comment.

**Comment by MrCircuit** [comment]
Hi there

The param of the the HandleKey interface will is filled in by an internal class of yours (KeyboardParam). Can you change its modifier to public? Otherwise, we can't use the custom keyboard handler at all...

Best regards
Uwe

**Comment by MrCircuit** [comment]
Thanks!
