### ISSUE TITLE
Cef binaries copied How disable ?

### ISSUE THREAD

**Issue by nurbat** [chromelyapps/Chromely#335]
![изображение](https://user-images.githubusercontent.com/5789051/127220689-74100084-9279-4293-b084-2184528c6514.png)
How do I disable copying ?

**Comment by mattkol** [comment]
@nurbat 

It is part of the nuget restore/build process on Windows.  This is not going to happen at runtime. 
To really stop that maybe you could delete the entire "build" folder in the nuget package.

![image](https://user-images.githubusercontent.com/18384207/127321542-530a764e-b24e-434b-a31d-48902c7143e5.png)

**Alternatively you can use just the dll instead of the nuget package.**

If you want to disable CEF binaries download at runtime, please look into:

````csharp
   var config = DefaultConfiguration.CreateForRuntimePlatform();
   config.CefDownloadOptions.AutoDownloadWhenMissing = false;
````

More info - https://github.com/chromelyapps/Chromely/blob/master/Documents/cef_binaries_download.md

**Comment by nurbat** [comment]
> It is part of the nuget restore/build process on Windows. This is not going to happen at runtime.
To really stop that maybe you could delete the entire "build" folder in the nuget package.

I will try to delete the build folder.

Maybe it is possible to disable it by specifying for example <CefBuild>false</CefBuild> in the solution file, think about such a solution if possible

**Comment by mattkol** [comment]
> Maybe it is possible to disable it by specifying for example <CefBuild>false</CefBuild> in the solution file, think about such a solution if possible

Isn't it just easier to create a post build event to override the CEF binaries downloaded?
This is will be a very rare requirement, in my opinion, but if you think it is useful, a PR will be appreciated.
