### ISSUE TITLE
What does Chromely offer extra over MS's WebView2?

### ISSUE THREAD

**Issue by Tony20221** [chromelyapps/Chromely#369]
What does Chromely offer extra over MS's WebView2? What are scenarios where Chromely would be a better choice?

**Comment by xplicit** [comment]
We have been using Chromely for two years, so that's my point of view why we choose it. We looked cross-platform .NET UI solution and have chosen Chromely.

Chromely works great on Windows7, Windows8, Windows10 and Windows11. Huge amount of users of our free software could check it during development and production testing.
Chromely works on MacOS (it has got several limitations with frameless window and some window-related commands which are not implemented yet, but at least it works).
Possible it works on linux (But I have never tested this configuration).

Cons: Chromely app has a big distribution size (our unpacked app is 400MB if based on Chromely 5.2, and 330MB Chromely 5.1)

Looks like WebView2 does not work on Mac and Linux at all:

https://github.com/MicrosoftEdge/WebView2Feedback/issues/1314
https://github.com/MicrosoftEdge/WebView2Feedback/issues/645

And I am not sure that support for these systems will be completed in near perspective, because Microsoft is interested in marketing their own platforms (It's Windows Desktop and Azure (.NET for linux server)). So tasks like implementing UI for linux/Mac is abandoned by Microsoft for now and may be forever.

Also there are open issue with installing WebView2 on Windows7
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1329

**Comment by mattkol** [comment]
@Tony20221, what @xplicit says captures it, in my opinion - cross platform mostly.
