### ISSUE TITLE
[MacOs] Crashed when start demo-projects/angular-react-vue: WirelessDiagnostics awd::metrics::protobuf_AddDesc_SimpleMetric_2eproto() + 44

### ISSUE THREAD

**Issue by seerkong** [chromelyapps/Chromely#384]
It crashes on macOS  when start the demo vue app, and can be started successfully when click the restart app in the crash report window.

https://github.com/chromelyapps/demo-projects
System version : Monterey version 12.5.1
dotnet core SDK VERSION : 6.0.400
JetBrains Rider version 2022.2.2

I changed the build cmd to
```
<Exec Command="cp -rf $(ProjectDir)vueapp\dist &quot;$(TargetDir)&quot;" />
```
in ChromelyVue.csproj

I have disabled System Integrity Protection, but not work.

but...on my another macbook, this vue demo can be started successfully  (System version : Monterey version 12.2.1, dotnet core SDK VERSION : 6.0.400. JetBrains Rider version 2022.2.2)
full crash log:
[crash.txt](https://github.com/chromelyapps/Chromely/files/9446196/crash.txt)

**Comment by mattkol** [comment]
@seerkong 

If you are able to restart it after the initial failure, it may be due to:

https://github.com/chromelyapps/demo-projects/issues/27
https://github.com/chromelyapps/demo-projects/issues/27#issuecomment-724633024

Please also note that the demos for - Angular, Vue, React, Blazor are just provided as-is as guides. 
Because these approaches are subject to many moving parts and third-party dependencies, it is advisable that issues are logged against [Cross Plat Demo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/Chromely.CrossPlat).

Thanks.
