### ISSUE TITLE
Net Core, main re-ran each time CEF opens a new window.

### ISSUE THREAD

**Issue by Damianu** [chromelyapps/Chromely#69]
I've updated to latest nuget version and noticed that each time CEF creates new window it also runs Main() of the program.. 
You can just simply add Console.WriteLine("Test") to Main() and then execute window.Run(args). 
Running the app and showing devtools will result in"Test" written to console 3 times, each time you close and open devtools it prints again.

**Comment by mattkol** [comment]
That seems like an expected behavior for multi process app. If you are not seeing this earlier it looks like you had your app set to Single Process. That is no longer supported. Please see [info](https://github.com/chromelyapps/Chromely/wiki/Upgrade-to-CefGlue-v68-and-CefSharp-v67).

What you see is an output for each process. If you check the Task Manager, you will something like this after the DevTool launch. Should be less one before the launch.

![image](https://user-images.githubusercontent.com/18384207/51909898-54b7b100-2393-11e9-9e7f-2bda5700e9be.png)

To not see this, you need to create a subprocess and set it.

````csharp
   //.WithCustomSetting(CefSettingKeys.BrowserSubprocessPath, path_to_subprocess)
   .WithCustomSetting(CefSettingKeys.SingleProcess, true)

````
None yet for CefGlue or Chromely.  It will be similar to subprocess  in CefSharp has - [please see here](https://github.com/cefsharp/CefSharp/tree/30ee538ce0e0d1d33ed838665758ec2061165224/CefSharp.BrowserSubprocess). I just started looking into migrating that to Chromely.

**Comment by Damianu** [comment]
I see, thanks for info. 
Also, if I'll make this subprocess, is there any way to get control over window from chromely? (For example change title/size of dev console or minimize it on start).

**Comment by mattkol** [comment]
This is not something I have looked at closely, but may be possible. 
I assume you are using CefGlue. The handler that launches the DevTool can be found [CefGlueContextMenuHandler.cs](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.CefGlue.Winapi/Browser/Handlers/CefGlueContextMenuHandler.cs#L133).

So you may want to look at a custom context handler. Please see where it is actually launched to see what parameters can be added -  https://github.com/chromelyapps/Chromely/blob/77184f882a72d0d243ca93f02c4a4a0624d71aa3/src/Chromely.CefGlue.Winapi/Browser/Handlers/CefGlueContextMenuHandler.cs#L133

The key to this may be in the Windows Style ..
https://github.com/chromelyapps/Chromely/blob/77184f882a72d0d243ca93f02c4a4a0624d71aa3/src/Chromely.CefGlue.Winapi/CefGlue/Structs/CefWindowInfo.cs#L156

So a custom handler will be set like:

````csharp
ChromelyConfiguration config = ChromelyConfiguration
                              .Create()
                              .....
                             .RegisterCustomHandler(CefHandlerKey.ContextMenuHandler, typeof(CustomContextMenuHandler));
````
Also check custom handling template  - [here](https://github.com/chromelyapps/Chromely/blob/master/src/Demos/Chromely.CefGlue.Winapi.Demo/README.md) and [Configuration wiki page](https://github.com/chromelyapps/Chromely/wiki/Configuration) for more guide.

Note that a custom handler will replace the default - [CefGlueContextMenuHandler.cs](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.CefGlue.Winapi/Browser/Handlers/CefGlueContextMenuHandler.cs#L133).
