### ISSUE TITLE
how to not display borders. Minimize, maximize, and close my own control in the code

### ISSUE THREAD

**Issue by 9527code** [chromelyapps/Chromely#81]
how to not display borders. Minimize, maximize, and close my own control in the code

**Comment by mattkol** [comment]
None of these options is supported. No plans and bandwidth to support them in the nearest future.

The "close" option will be easy to do for most developers who want to "dig" into the code. 
Other options may be a little bit involved.

**Comment by 9527code** [comment]
in the Electron i can 
`const {BrowserWindow} = require('electron')
let win = new BrowserWindow({width: 800, height: 600, **frame: false**})
win.show()`
why i need this?
Because the default border is too ugly

**Comment by FrankPfattheicher** [comment]
@mattkol i have looked at this - i think we could inclue an option "frameless" ? 
Should i do that?

**Comment by Fiahblade** [comment]
Removing the frame will also remove the Aero Snap feature etc. Correct?

**Comment by FrankPfattheicher** [comment]
@Fiahblade jes it does.

**Comment by FrankPfattheicher** [comment]
@9527code 
HostFrameless option added.
```
ChromelyConfiguration
                .Create()
                .WithLoadingCefBinariesIfNotFound(true)
                **.WithFramelessHost()**
                .WithAppArgs(args)
```
master - commit 349342f95fa7761e1b9b15661c24399cdeda3f3b

**Comment by mattkol** [comment]
@FrankPfattheicher thanks for looking into this.

Sorry I closed it earlier in an error. I was going to respond to you then got distracted and put the phone in my pocket ....

**Comment by FrankPfattheicher** [comment]
@mattkol  shit happens ;-)
No problem !

**Comment by 9527code** [comment]
@FrankPfattheicher thx a lot!

**Comment by NovusTheory** [comment]
Having recently come across Chromely. I tested it out and immediately look up a frameless option. I didn't find one right away but I found this issue on it. I want to provide a little bit of input. As per https://github.com/chromelyapps/Chromely/commit/349342f95fa7761e1b9b15661c24399cdeda3f3b the option to add frameless was added but you did mention that it would remove aero snap features. I personally find this feature extremely important as I use it on a daily basis dragging my windows off to the side or up top to maximize them.

Electron's frameless still supports aero snap and I would love to see this changed. I did a lot of Googling and forked the repo to try it out but it is much more effort since it seems chrome being a child process it takes WinApi priority and I wasn't quite able to get it working. Window resize and dragging was not a feature I could properly add due to (likely) the above mentioned but can't confirm. On a side note of that I would love to see `-webkit-app-region: drag` as an available usage and I did find a repository [here](https://github.com/qwqcode/CefSharpDraggableRegion) which seems to implement that. This would go nicely with a proper aero snap frameless window.

**Comment by FrankPfattheicher** [comment]
@NovusTheory the current frameless implementation is a quick one ;-)
I agree that aero snap should be there, but currently i only stated it is NOT there for this version - we should try to add it later.

**Comment by NovusTheory** [comment]
@FrankPfattheicher Totally understand it being a quick one as what I've seen from my own programming to try to add it is much more difficult. I do hope proper implementation is added soon as a quick and dirty frameless window usually has lots of missing functionality.
