### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by RupertAvery** [chromelyapps/Chromely#91]
How are controllers dependency injected?

I tried creating a SimpleContainer and registering a dependency class and pass it onto the ChromelyConfiguration

```
IChromelyContainer container = new SimpleContainer();
container.RegisterInstance<IService>("myService", new MyService());
ChromelyConfiguration config = ChromelyConfiguration
                                              .Create(container)
```

But if I put anything in the constructor of my Controller, it never gets instantiated. The controller class is only instantiated if the constructor has no arguments.

```
public MyController(IService myservice)
```

**Comment by mattkol** [comment]
@RupertAvery yes, that is by design. Only default constructor. The Controller in this regard is just a placeholder, a container if you like for actionable methods.

You can still achieve what you want though, but not via constructor dependency injection.

Something like:

On initialization:
```
IChromelyContainer container = new SimpleContainer();
container.RegisterInstance<IService>("myService", new MyService());
ChromelyConfiguration config = ChromelyConfiguration
                                              .Create(container)
```

In controller:
```
        private ChromelyResponse Execute(ChromelyRequest request)
        {
            var response = new ChromelyResponse(request.Id);
             ----
           var servicei = IoC.GetInstance(typeof(MyService), "myService");
            ---
            return response;
        }
```

**Comment by RupertAvery** [comment]
Thanks, however, it kind of breaks the whole point of dependency injection.

I'm curious, is this an architectural limitation?

Also noticed that the framework creates the controllers only once, whereas in MVC the controllers are created per request. This may have implications on how objects should be instantiated, if created in the constructor.

**Comment by RupertAvery** [comment]
I've taken a look at the code and seen how it works, thanks!

**Comment by mattkol** [comment]
@RupertAvery yw.

Chromely is intentionally made super simple for most developers. But also flexible for advanced developers like you. If you want to make it work the way you want this is achievable. 

The Controller attribute was designed intentionally for that - [ControllerPropertyAttribute](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/RestfulService/ControllerPropertyAttribute.cs). So you can leverage the [Name](https://github.com/chromelyapps/Chromely/blob/cab22d87f8be8669045c79991f9516c69fc8877d/src/Chromely.Core/RestfulService/ControllerPropertyAttribute.cs#L23) and [Route](https://github.com/chromelyapps/Chromely/blob/cab22d87f8be8669045c79991f9516c69fc8877d/src/Chromely.Core/RestfulService/ControllerPropertyAttribute.cs#L28) properties for that.

Instead of creating the controller object on the fly using Activator, you use Name and the Route to access a pre-registered contoller in the Container.

So you will have something like:

```
    [ControllerProperty(Name = "DemoController001", Route = "democontroller001")]
    public class DemoController : ChromelyController
    {
    }
```

```
IChromelyContainer container = new MoreSoftistcatedContainer();
container.RegisterInstance<IService>("myService", new MyService());
container.RegisterInstance<IService>("DemoController001", new MyController());
ChromelyConfiguration config = ChromelyConfiguration
                                              .Create(container)
```
.. and retrieve the controller object in the RouteScanner.

If this  is considered a common requirement we can look into implementing it, but I bet you most developers will forget to add unique name and route which may cause collision.

@Fiahblade @FrankPfattheicher

**Comment by RupertAvery** [comment]
I understand, it's just that developers may be coming from an MVC background, so it might make sense to follow existing conventions, such as using HttpPost, HttpGet, Route attributes (Is copying an API for the purpose of compatibility a problem?)  and also perhaps using .net core's existing IServiceCollection would also help devs looking to port existing code over.

**Comment by mattkol** [comment]
@RupertAvery actually this is "following existing convention". But not really MVC per se - [NancyFx](https://github.com/NancyFx/Nancy/blob/master/samples/Nancy.Demo.Async/MainModule.cs).

Nothing here is written in stone, but simplicity is the key word. So I think we should consider changes but still keeping the architecture as simple as possible.

**Comment by RupertAvery** [comment]
Sure. 

I've written a MVC-style approach that only requires ChromelyConfiguration to have an interface, and have most everything in Chromely.CefSharp.WinApi that uses ChromelyConfiguration 
 to change to IChromelyConfiguration, so a rather small change.

It's a separate project, right now I've named in Chromely.Mvc, maybe name it Chromely.Restful.Mvc?  Or I could name it something else if I can't use Chromely.

Initialization looks like this:

```charp
                IChromelyConfiguration config = MvcChromelyConfiguration
                                        .Create()
                                        .WithAppArgs(args)
                                        .WithHostMode(WindowState.Normal, true)
                                        .WithHostTitle("delphi")
                                        .WithHostIconFile("chromely.ico")
                                        .WithStartUrl(startUrl)
                                        .WithLogFile("logs\\chromely.cef_new.log")
                                        .WithLogSeverity(LogSeverity.Info)
                                        .UseDefaultLogger()
                                        .UseDefaultResourceSchemeHandler("local", string.Empty)
                                        .UseDefaultHttpSchemeHandler("http", "chromely.com")
                                        .WithControllersAssembly(Assembly.GetExecutingAssembly())
                                        .UseMvc((routes) =>
                                        {
                                            routes.MapRoute("default", "/{controller}/{action}");
                                        })
                                        .RegisterServices((serviceCollection) =>
                                        {
                                            serviceCollection.AddTransient<ITimesheetBL, TimesheetBL>();
                                            serviceCollection.AddSingleton<ILocalDataBL, LocalDataBL>();
                                            serviceCollection.AddSingleton<IOracleService, OracleService>();
                                        })
                                        .UseDefaultJsHandler("boundControllerAsync", true);
```
So not too different. There are some attributes HttpGet, HttpPost, etc. Controllers can look like this:

```charp
    public class DelphiController : ChromelyController
    {
        private ITimesheetBL _timesheetBL;
        private ILocalDataBL _localDataBL;

        public DelphiController(ITimesheetBL timesheetBL, ILocalDataBL localDataBL)
        {
            _timesheetBL = timesheetBL;
            _localDataBL = localDataBL;
        }

        [HttpGet]
        public ChromelyResponse IsFirstRun(ChromelyRequest request)
        {
            ChromelyResponse response = new ChromelyResponse();
            response.Data = _localDataBL.IsFirstRun();
            return response;
        }

        [HttpGet]
        public ChromelyResponse GetLocalProjectTasks(ChromelyRequest request)
        {
            ChromelyResponse response = new ChromelyResponse();
            response.Data = _localDataBL.GetProjectTasks();
            return response;
        }

```

So it's only a matter of configuration, no major changes on Chromely side to use this method.

Controllers are created on demand (transient) and using the serviceProvder created inside the configuration, so Dependency Injection just works.

**Comment by mattkol** [comment]
@RupertAvery ChromelyConfiguration is central to how Chromely works. Like you I love to program to interface too, as a matter of principle. But not everything is "better achieved" by interfaces. There was a reason why this approach was chosen. Don't get me wrong, I am not saying it cannot be changed, but I am not seeing a strong reason with what you want to do.

- What you want to do can be done in a less intrusive way
- Since ChromelyConfiguration was made a Singleton (for a good reason that I can explain), passing it around in classes is no longer required. I have just never had bandwidth to clean that up.
- This change will also require huge regression testing, and that will require hours that I am not sure @Fiahblade @FrankPfattheicher or I may have that bandwidth for at the moment.
- Also ChromelyConfiguration has singleton invocations all over the place, this will break that approach, as the developer may have a different implementations.  

https://github.com/chromelyapps/Chromely/blob/15343a0ca85929c75af57edc0e36e6801dd42236/src/Chromely.CefSharp.Winapi/Browser/Handlers/CefSharpContextMenuHandler.cs#L40
https://github.com/chromelyapps/Chromely/blob/1869a03e3e4d9846b1516d188ad51f23e603dfd6/src/Chromely.CefGlue/Browser/Handlers/CefGlueContextMenuHandler.cs#L41
https://github.com/chromelyapps/Chromely/blob/d4486da394a6297f711fe2a230c63e334b6cceb4/src/Chromely.CefSharp.Winapi/Browser/Internals/ChromiumWebBrowserExtension.cs#L249

But I am ready to learn if there are easier way around that.

Why is ChromelyConfiguration a singleton? If a developer wants to have more than one window opened in a process, CefGlue and CefSharp will throw an exception if you register the the same scheme handlers and resource handlers more than once. Also there are cases like the link I sent where changes are easier done by accessing functionalities in a singleton pattern without a huge change to the framework. But the primary reason is the scheme and resource handlers registation.

**My suggestion for now is to use extension method or inheritance, then gradually we can have bandwidth for this change if need be.**

**Comment by RupertAvery** [comment]
Thanks for the feedback! I've rewritten it as a separate configuration object, which works out much simpler and avoids changes to Chromely.

**Comment by mattkol** [comment]
@RupertAvery yw.

But you are still going to share that with us, right? The attributes on Controller actions and IOC constructor injection are still something that I think we should have. @Fiahblade @FrankPfattheicher and I can help include that.

**Comment by RupertAvery** [comment]
Absolutely. Right now it's a standalone "add-on" to Chromely, as the main entry point is the CefSharpBoundObject which is injected, it was easy to create a new set of handlers without any Chromely code adjustments.

Here are the features I've implemented:

* Use MVC's convention-based approach to writing and wiring up controllers.
* Use .NET Core's built-in `IServiceCollection` for dependency injection.
* Constructor and property injection on controller classes.
* Controller classes are transient services - created for each request.
* Annotate Controller action methods with `HttpGet`, `HttpPost` etc
* Model binding

Model binding means you can write your methods without ChromelyResponse and ChromelyRequest:

```
public IEnumerable<WeatherData> GetWeatherForecast(DateTime date, string location)
```

Of course, there is still a lot of work to do with model binding, but it currently works with Get and Post and most basic data types, object graphs and arrays.  

It's available here https://github.com/RupertAvery/Chromely.Mvc

**Comment by FrankPfattheicher** [comment]
@RupertAvery i now added DI support for chromely controllers with commit e77afd12bf2c7e700f8f39992e252f91b7d4c579.
Do you like to test if this helps you?

**Comment by mattkol** [comment]
> Absolutely. Right now it's a standalone "add-on" to Chromely, ...
> It's available here https://github.com/RupertAvery/Chromely.Mvc

@RupertAvery thanks. I will surely take Chromely.Mvc for a ride!

Please will you add Chromely.Mvc  to: 
https://github.com/chromelyapps/Chromely/issues/63
https://github.com/chromelyapps/Chromely/wiki/A-List-of-Apps-Built-with-Chromely

**Comment by RupertAvery** [comment]
I just realized I don't know how to update another wiki... I tried cloning
locally and pushing, but then I don't have rights.

**Comment by mattkol** [comment]
@RupertAvery should work with a PR.

**Comment by RupertAvery** [comment]
@mattkol just to let you know I've updated Chromely.Mvc with Chromely 5.0.0.6.

https://github.com/RupertAvery/Chromely.Mvc

**Comment by mattkol** [comment]
@RupertAvery thanks for the update.
